version: '3.5'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql:rw,z
    expose:
      - 5432
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_EXTERNAL_PORT=15432
      - POSTGRES_DB=mqtt-task

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqttsende:
    image: mqttms
    container_name: 'mqttsender'
    command: sh -c "node /app/dist/apps/mqtt-first-ms/main.js"
    volumes:
      - ./config:/app/config
    restart: always
    expose:
      - 3001
    ports:
      - "3001:3001"

  mqttlistener:
    image: mqttms
    container_name: 'mqttlistener'
    command: sh -c "node /app/dist/apps/mqtt-second-ms/main.js"
    volumes:
      - ./config:/app/config
    restart: always
    expose:
      - 3002
    ports:
      - "3002:3002"
