version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql:rw,z
    expose:
      - 5432
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_EXTERNAL_PORT=15432
      - POSTGRES_DB=mqtt-task

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf