database:
  type: 'postgres'
  host: 'postgres'
  port: 5432
  username: 'postgres'
  password: 'test'
  database: 'mqtt-task'

microservices:
  mqttSender:
    url: 'http://localhost:3001'
    port: '3001'

  mqttListener:
    url: 'http://localhost:3002'
    port: '3002'

mqttConfig:
  protocol: 'mqtt'
  host: 'mosquitto'
  port: 1883
  username: 'user'
  password: 'password'
  clean: true
  connectTimeout: 4000
  reconnectPeriod: 1000

topics:
  mainTopic: 'mainTopic'
