database:
  type: 'postgres'
  host: 'localhost'
  port: 15432
  username: 'postgres'
  password: 'test'
  database: 'test-task-db'

microservices:
  mqttFirst:
    url: 'http://localhost:3001'
    port: '3001'

  mqttSecond:
    url: 'http://localhost:3002'
    port: '3002'

mqttConfig:
  protocol: 'mqtt'
  host: 'localhost'
  port: 1883
  username: 'user'
  password: 'password'
  clean: true
  connectTimeout: 4000
  reconnectPeriod: 1000
